export const GET_DIR = 'GET_DIR'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_SELECTED = 'CHANGE_SELECTED'
export const GET_SORT = 'GET_SORT'
export const GET_APITITLE = 'GET_APITITLE'
export const GET_DOCTITLE = 'GET_DOCTITLE'
